# Generated by Django 2.1.2 on 2020-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20200515_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='selection.Course'),
        ),
    ]
